from flask_restful import reqparse

parser = reqparse.RequestParser()
parser.add_argument('id', required=True)
parser.add_argument('name', required=True)
parser.add_argument('username', required=True, type=int)
parser.add_argument('password', required=True)
parser.add_argument('phone', required=True)
parser.add_argument('mail', required=True)
parser.add_argument('activation_code', required=True)
parser.add_argument('start_of_activation', required=True)
parser.add_argument('date_of_the_end_activation', required=True)
parser.add_argument('IP', required=True)
parser.add_argument('registration_date', required=True)
parser.add_argument('status', required=True)
parser.add_argument('number_of_bans', required=True)